---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  annotations:
    fluxcd.io/automated: "true"
spec:
  chart:
    spec:
      chart: keycloak
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: 5.1.6
  values:
    image: 
      repository: jakoberpf/keycloak
      tag: 15.1.1-debian-10
    service:
      type: ClusterIP
    postgresql:
      image:
        repository: jakoberpf/postgresql
        tag: 13-debian-10
  interval: 10m0s

---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: bitnami
spec:
  interval: 10m0s
  url: https://charts.bitnami.com/bitnami