mariadb:
  enabled: true
  persistence:
    enabled: true
    pvc: 
      name: anonaddy-mariadb-data-live
redis:
  enabled: true
  persistence:
    enabled: true
    pvc: 
      name: anonaddy-redis-data-live
ingress:
  enabled: true
  hosts: 
    - host: anonaddy.erpf.de
  tls:
    enabled: true
    redirect: false
  istioGateway:
    enabled: true
  certManager:
    enabled: true
    issuerRef: 
      name: cloudflare-letsencrypt-staging
