apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-minio-0
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  storageClassName: rclone
  selector:
    matchLabels:
      name: minio-rclone-dropbox
