apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-root-user
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: "5m"
  target:
    name: minio-root-user
  data:
  - secretKey: root-user
    remoteRef:
      key: applications/minio/root-user
      property: root-user
  - secretKey: root-password
    remoteRef:
      key: applications/minio/root-user
      property: root-password
