---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vaultwarden-token
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: "1m"
  target:
    name: vaultwarden-token
  data:
  - secretKey: token
    remoteRef:
      key: vaultwarden/token
      property: adminToken

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vaultwarden-smtp
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: "1m"
  target:
    name: vaultwarden-smtp
  data:
  - secretKey: user
    remoteRef:
      key: vaultwarden/smtp
      property: emailUser
  - secretKey: password
    remoteRef:
      key: vaultwarden/smtp
      property: emailPassword