config:
  # storage:
  #   type: postgres
  #   path: "postgres://user:password@127.0.0.1:5432/gatus?sslmode=disable"
  # https://github.com/TwiN/gatus#oidc
  # https://github.com/TwiN/gatus#metrics
  endpoints:
    - name: Keycloak - Authentication
      url: "https://iam.erpf.de"
      client:
        insecure: false
        ignore-redirect: false
        timeout: 10s
      conditions:
        - "[STATUS] == 200"
    - name: Vault - Secrets Manager
      url: "https://vault.erpf.de"
      client:
        insecure: false
        ignore-redirect: false
        timeout: 10s
      conditions:
        - "[STATUS] == 200"
    - name: Vaultwarden - Password Manager
      url: "https://vaultwarden.erpf.de"
      client:
        insecure: false
        ignore-redirect: false
        timeout: 10s
      conditions:
        - "[STATUS] == 200"
    - name: Proxmox - Backup
      url: "https://backup.proxmox.erpf.de"
      client:
        insecure: false
        ignore-redirect: false
        timeout: 10s
      conditions:
        - "[STATUS] == 200"
    - name: Proxmox - Development
      url: "https://development.proxmox.erpf.de"
      client:
        insecure: false
        ignore-redirect: false
        timeout: 10s
      conditions:
        - "[STATUS] == 200"
    - name: Proxmox - Production
      url: "https://production.proxmox.erpf.de"
      client:
        insecure: false
        ignore-redirect: false
        timeout: 10s
      conditions:
        - "[STATUS] == 200"
