config:
  # storage:
  #   type: postgres
  #   path: "postgres://user:password@127.0.0.1:5432/gatus?sslmode=disable"
  # https://github.com/TwiN/gatus#oidc
  # https://github.com/TwiN/gatus#metrics
  endpoints:
    - name: Keycloak - Authentication
      url: "https://iam.erpf.de"
      client:
        insecure: false
        ignore-redirect: false
        timeout: 10s
      conditions:
        - "[STATUS] == 200"
    - name: Vault - Secrets Manager
      url: "https://vault.erpf.de"
      client:
        insecure: false
        ignore-redirect: false
        timeout: 10s
      conditions:
        - "[STATUS] == 200"
    - name: Vaultwarden - Password Manager
      url: "https://vaultwarden.erpf.de"
      client:
        insecure: false
        ignore-redirect: false
        timeout: 10s
      conditions:
        - "[STATUS] == 200"
    - name: Zerotier - SDN based on the zerotier protocol
      url: "https://zerotier.erpf.de"
      client:
        insecure: false
        ignore-redirect: false
        timeout: 10s
      conditions:
        - "[STATUS] == 200"
    - name: Grafana - Monitoring and Logging Dashboards
      url: "https://grafana.erpf.de"
      client:
        insecure: false
        ignore-redirect: false
        timeout: 10s
      conditions:
        - "[STATUS] == 200"
    - name: Netmaker - SDN based on the wireguard protocol
      url: "https://dashboard.netmaker.erpf.de"
      client:
        insecure: false
        ignore-redirect: false
        timeout: 10s
      conditions:
        - "[STATUS] == 200"
    - name: Proxmox - Pineapple Cluster
      url: "https://pineapple.proxmox.erpf.de"
      client:
        insecure: false
        ignore-redirect: false
        timeout: 10s
      conditions:
        - "[STATUS] == 200"
    - name: Proxmox - Mango Cluster
      url: "https://mango.proxmox.erpf.de"
      client:
        insecure: false
        ignore-redirect: false
        timeout: 10s
      conditions:
        - "[STATUS] == 200"
