---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-admin-credentials
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: "1m"
  target:
    name: keycloak-admin-credentials
  data:
  - secretKey: password
    remoteRef:
      key: applications/keycloak
      property: KEYCLOAK_PASSWORD
  - secretKey: user
    remoteRef:
      key: applications/keycloak
      property: KEYCLOAK_USER
