persistence:
  enabled: true
  pvc:
    name: keycloak-data-live
ingress:
  enabled: true
  hosts: 
    - host: iam.erpf.de
  tls:
    enabled: true
    redirect: false
  istioGateway:
    enabled: true
  certManager:
    enabled: true
    issuerRef: 
      name: cloudflare-letsencrypt-prod