teleport-cluster:
  persistence:
    enabled: true
ingress:
  enabled: true
  hosts: 
    - host: teleport.erpf.de
  tls:
    enabled: true
    redirect: false
  istioGateway:
    enabled: true
  certManager:
    enabled: true
    issuerRef: 
      name: cloudflare-letsencrypt-prod