teleport-cluster:
  clusterName: teleport.erpf.de
  acme: true
  acmeEmail: "jakob@erpf.de"
  persistence:
    enabled: false
    existingClaimName: teleport-data-live
    extraArgs:
      - --insecure-no-tls

ingress:
  enabled: true
  hosts: 
    - host: teleport.erpf.de
  tls:
    enabled: true
    redirect: true
  istioGateway:
    enabled: true
