apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.fullname" . }}-cluster-config
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
data:
  app.db.database: "{{ .Values.cluster.dbName }}"
  app.db.cluster.name: "{{ .Values.cluster.clusterName }}"
  app.db.cluster.replication.db: "{{ .Values.cluster.replicationName }}"
  app.db.pool.backends: "{{ range $i, $e := .Values.cluster.nodes }}{{ if $i }},{{ end }}{{ $i }}:{{ $.Values.cluster.name }}-db-node-{{ $i }}.{{ $.Values.cluster.name }}-db::::{{ end }}"