apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}-cluster
  labels:
    type: cluster
    system: {{ .Values.cluster.name }}
    # {{- include "postgres.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    type: cluster
    system: {{ .Values.cluster.name }}
    # {{- include "postgres.selectorLabels" . | nindent 4 }}
