---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubesphere-tls
spec:
  secretName: kubesphere-tls
  issuerRef:
    name: cloudflare-letsencrypt-prod
    kind: ClusterIssuer
  commonName: kubesphere.erpf.de
  dnsNames:
    - kubesphere.erpf.de
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"  
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "istio-system"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "istio-system"

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubesphere-cluster-tls
spec:
  secretName: kubesphere-cluster-tls
  issuerRef:
    name: cloudflare-letsencrypt-prod
    kind: ClusterIssuer
  commonName: kubesphere.zelos.k8s.erpf.de
  dnsNames:
    - kubesphere.zelos.k8s.erpf.de
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"  
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "istio-system"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "istio-system"