---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  annotations:
    fluxcd.io/automated: "true"
spec:
  chart:
    spec:
      chart: vault
      sourceRef:
        kind: HelmRepository
        name: hashicorp
      version: 0.17.1
  values:
    ui:
      enabled: false
      #   server:
          # extraSecretEnvironmentVars:
          #   - envName: AWS_ACCESS_KEY_ID
          #     secretName: eks-creds
          #     secretKey: AWS_ACCESS_KEY_ID
          #   - envName: AWS_SECRET_ACCESS_KEY
          #     secretName: eks-creds
          #     secretKey: AWS_SECRET_ACCESS_KEY
          # ha:
          #   enabled: true
          # config: |
          #     ui: true

          #     listener "tcp" {
          #       address = "[::]:8200"
          #       cluster_address = "[::]:8201"
          #     }
  interval: 10m0s

---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: hashicorp
spec:
  interval: 10m0s
  url: https://helm.releases.hashicorp.com