apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zerotier-admin-credentials
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: "5m"
  target:
    name: zerotier-admin-credentials
  data:
  - secretKey: username
    remoteRef:
      key: applications/zerotier/admin
      property: username
  - secretKey: password
    remoteRef:
      key: applications/zerotier/admin
      property: password
