ingress:
  enabled: true
  hosts: 
    - host: zerotier.erpf.de
  tls:
    enabled: true
    redirect: true
  istioGateway:
    enabled: true
  certManager:
    enabled: true
    issuerRef: 
      name: cloudflare-letsencrypt-prod
