deployment:
  image: quay.io/go-skynet/local-ai:v1.15.0
  env:
    threads: 14
    contextSize: 512
    modelsPath: "/models"
models:
  forceDownload: false
  list:
    - url: "https://gpt4all.io/models/ggml-gpt4all-j.bin"
      # basicAuth: base64EncodedCredentials
  persistence:
    enabled: true
    size: 10Gi
    accessModes:
      - ReadWriteOnce
  auth:
    # Optional value for HTTP basic access authentication header
    basic: "" # 'username:password' base64 encoded
service:
  type: ClusterIP
  annotations: {}

# https://github.com/go-skynet/helm-charts/blob/main/charts/local-ai/values.yaml
# https://github.com/go-skynet/LocalAI#example-use-gpt4all-j-model
# https://github.com/charmbracelet/mods?ref=console.dev

