namespace: grafana
resources:
  - certificate.yaml
  - gateway.yaml
  - virtualservice.yaml
  - secrets.yaml
helmCharts:
  - name: grafana
    repo: https://grafana.github.io/helm-charts   
    releaseName: grafana
    valuesFile: values.yaml
